version: "3.9"
services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        command: ./wait-for-it.sh mongo:27017 -- npm run dev
        ports:
            - "3000:3000"
        env_file:
            - ../.env
        environment:
            NODE_ENV: development
            MONGODB_USERNAME:
            MONGODB_PASSWORD:
            MONGODB_CLUSTER:
            MONGODB_DBNAME:
            JWT_SECRET:
        volumes:
            - ..:/app
            - /app/node_modules
        tty: true
        stdin_open: true

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME:
            MONGO_INITDB_ROOT_PASSWORD:
        volumes:
            - ../data/mongo:/data/db
